version: '3.8'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    build: .
    image: airtonomy.azurecr.io/eddm/kafka:dev
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # Setup some development settings
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 7
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: unless-stopped
